# Generated by Django 4.2.2 on 2023-07-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date_of_Schedule',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Time_of_Schedule',
            field=models.CharField(max_length=100),
        ),
    ]
