# Generated by Django 4.2.2 on 2023-07-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_date_of_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date_of_Schedule',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Time_of_Schedule',
            field=models.TimeField(),
        ),
    ]
