# Generated by Django 4.2.2 on 2023-06-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='media')),
                ('price', models.FloatField(default='10')),
                ('EnteredBy', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Pro',
            },
        ),
    ]
