# Generated by Django 4.2.2 on 2023-07-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Name', models.CharField(max_length=100)),
                ('Doctor_Specialisation', models.CharField(max_length=100)),
                ('Doctor_Contact_Number', models.CharField(max_length=10)),
                ('Doctor_Location', models.CharField(max_length=100)),
                ('EnteredBy', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Doc',
            },
        ),
    ]
