# Generated by Django 4.2.2 on 2023-07-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctors_doctor_specialisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Doctor_Specialisation',
            field=models.CharField(max_length=100),
        ),
    ]
