# Generated by Django 4.2.2 on 2023-07-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='Date',
            field=models.DateField(default=None),
        ),
    ]
